import type { Metadata } from "next"
import "./globals.scss"
import { Onest } from 'next/font/google'

const onest = Onest({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={onest.className}>
        {children}
      </body>
    </html>
  );
}
